#!/usr/bin/env sh
[ "$CI" = "true" ] && echo "🚀 Skipping Husky in CI/CD" && exit 0
. "$(dirname "$0")/_/husky.sh"

echo "compare-env file is Running...."
bash scripts/compare-env.sh
echo "completed compare-env file."