name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npx pnpm install

      - name: Format and Lint Codes
        run: npx pnpm format & npx pnpm lint

      - name: Check for Formatting Changes
        run: |
            if ! git diff --quiet; then
             echo "needs_commit=true" >> $GITHUB_ENV
            else 
              echo "needs_commit=false" >> $GITHUB_ENV
            fi
            
      - name: Set git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Formatting Changes
        if: env.needs_commit == 'true'
        run: |
          git add .
          git commit -am "Auto-format code in ci cd project"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Run prisma generate
        run: npx pnpm prisma generate

      - name: Build the project
        run: npx pnpm build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd nestjs-ci-cd
            git pull origin main
            docker compose down
            docker compose up --build -d
